version: 0.6.{build}

branches:
  only:
  - master
  - /dev-.*/

configuration:
  - Release
# XXX: LNK1104: cannot open file 'python27_d.lib'
  # - Debug

clone_folder: c:\projects\triton

environment:
  # python is automatically found by the find_package's
  CAPSTONE_INCLUDE_DIRS: c:\projects\triton\build\capstone-3.0.4\include
  BOOST_ROOT: c:\Libraries\boost_1_62_0

  matrix:
    - platform: Win32
      LIEF_ZIP: windows_x86_lief-0.7.0_py2.7.zip
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-3.0.4\msvc\%configuration%\capstone.lib
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.5.0-x86-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.5.0-x86-win\bin\libz3.lib
      Z3_PKG_NAME: z3-4.5.0-x86-win
      CMAKE_TEMPLATE: Visual Studio 14 2015
      PYTHON: "C:\\Python27"

    #- platform: Win32
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-3.0.4\msvc\%configuration%\capstone.lib
    #  Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.5.0-x86-win\include
    #  Z3_LIBRARIES: c:\projects\triton\build\z3-4.5.0-x86-win\bin\libz3.lib
    #  Z3_PKG_NAME: z3-4.5.0-x86-win
    #  CMAKE_TEMPLATE: Visual Studio 15 2017
    #  PYTHON: "C:\\Python27"

    - platform: x64
      LIEF_ZIP: windows_x64_lief-0.7.0_py2.7.zip
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-3.0.4\msvc\x64\%configuration%\capstone.lib
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.5.0-x64-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.5.0-x64-win\bin\libz3.lib
      Z3_PKG_NAME: z3-4.5.0-x64-win
      CMAKE_TEMPLATE: Visual Studio 14 2015 Win64
      PYTHON: "C:\\Python27-x64"

    #- platform: x64
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-3.0.4\msvc\x64\%configuration%\capstone.lib
    #  Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.5.0-x64-win\include
    #  Z3_LIBRARIES: c:\projects\triton\build\z3-4.5.0-x64-win\bin\libz3.lib
    #  Z3_PKG_NAME: z3-4.5.0-x64-win
    #  CMAKE_TEMPLATE: Visual Studio 15 2017 Win64
    #  PYTHON: "C:\\Python27-x64"

install:
  - set PATH=%PYTHON%;%PATH%
  - cmd: cd c:\projects\triton
  - cmd: mkdir build
  - cmd: cd build
  - cmd: echo Downloading z3...
  - cmd: appveyor DownloadFile https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/%Z3_PKG_NAME%.zip
  - cmd: 7z x %Z3_PKG_NAME%.zip
    # Install z3 in the path
  - set PATH=%Z3_PKG_NAME%/bin;%PATH%
  - cmd: echo Downloading capstone...
  - cmd: appveyor DownloadFile https://github.com/aquynh/capstone/archive/3.0.4.zip
  - cmd: 7z x 3.0.4.zip
  - cmd: echo Building capstone...
# This is required because capstone's slns/vcxprojs file have been made with an old version of MSVC which is not a problem in itself,
# the issue will show up when trying to link capstone.lib (generated with an old toolset) into triton that is generated with the new toolset.
# This result in annoying linking errors (sprintf/and similar functions don't get resolved) - we could also link legacy_stdio_definitions.lib to triton
# but I would rather build everything I can with the same toolset:
#   http://stackoverflow.com/questions/32418766/c-unresolved-external-symbol-sprintf-and-sscanf-in-visual-studio-2015
# The switch /p:PlatformToolset allows you to override the toolset version specified in the solution/project files :-)
  - cmd: msbuild capstone-3.0.4\msvc\capstone.sln /p:Configuration=%configuration% /p:Platform=%platform% /p:PlatformToolset=v140 /t:capstone_static /m
  - cmd: echo Running cmake...
  - cmd: cmake .. -G "%CMAKE_TEMPLATE%"
    # Install LIEF
  - cmd: echo Downloading LIEF...
  - cmd: appveyor DownloadFile https://github.com/lief-project/LIEF/releases/download/0.7.0/%LIEF_ZIP%
  - cmd: echo Install LIEF...
  - cmd: python -m pip install %LIEF_ZIP%

#build:
# Build manually until we can build every target. For now, we can't run test-python
# target without installation
#  parallel: true
#  project: c:\projects\triton\build\triton.sln

build_script:
  - cmd: msbuild c:\projects\triton\build\triton.sln  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:python-triton /m:3
    #  - cmd: cmake --build . --config release

test_script:
  - cmd: cmake --build . --config Release --target check

after_test:
  # Check installation
  - cmd: cmake --build . --config Release --target install

  # generate artifact
  - cmd: cd src\libtriton\%configuration%
  - cmd: copy ..\..\..\%Z3_PKG_NAME%\bin\libz3.dll libz3.dll
  - cmd: move triton.dll triton.pyd
  - cmd: if "%platform%"=="Win32" 7z a -t7z ..\..\..\..\triton.x86.release.7z *
  - cmd: if "%platform%"=="x64" 7z a -t7z ..\..\..\..\triton.x64.release.7z *

artifacts:
  - path: triton.*.7z
