version: 0.9.{build}

branches:
  only:
  - master
  - /dev-.*/

configuration:
  - Release

clone_folder: c:\projects\triton

environment:
  CAPSTONE_INCLUDE_DIRS: c:\projects\triton\build\capstone-4.0.2\include
  PLATFORM_TOOLSET: v142
  CMAKE_TEMPLATE: Visual Studio 16 2019

  matrix:
    - platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python36
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-4.0.2\msvc\%configuration%\capstone.lib
      LIEF_VERSION: 0.10.1
      LIEF_ZIP: lief-0.10.1-cp36-cp36m-win32.whl
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.8.9-x86-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.8.9-x86-win\bin\libz3.lib
      Z3_PKG_NAME: z3-4.8.9-x86-win
      PYTHON_VERSION: 3.6

    - platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python37
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-4.0.2\msvc\%configuration%\capstone.lib
      LIEF_VERSION: 0.10.1
      LIEF_ZIP: lief-0.10.1-cp37-cp37m-win32.whl
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.8.9-x86-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.8.9-x86-win\bin\libz3.lib
      Z3_PKG_NAME: z3-4.8.9-x86-win
      PYTHON_VERSION: 3.7

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python36-x64
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-4.0.2\msvc\x64\%configuration%\capstone.lib
      LIEF_VERSION: 0.10.1
      LIEF_ZIP: lief-0.10.1-cp36-cp36m-win_amd64.whl
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.8.9-x64-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.8.9-x64-win\bin\libz3.lib
      Z3_PKG_NAME: z3-4.8.9-x64-win
      PYTHON_VERSION: 3.6

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python37-x64
      CAPSTONE_LIBRARIES: c:\projects\triton\build\capstone-4.0.2\msvc\x64\%configuration%\capstone.lib
      LIEF_VERSION: 0.10.1
      LIEF_ZIP: lief-0.10.1-cp37-cp37m-win_amd64.whl
      Z3_INCLUDE_DIRS: c:\projects\triton\build\z3-4.8.9-x64-win\include
      Z3_LIBRARIES: c:\projects\triton\build\z3-4.8.9-x64-win\bin\libz3.lib
      Z3_PKG_NAME: z3-4.8.9-x64-win
      PYTHON_VERSION: 3.7


install:
  - set PATH=%PYTHON%;%PATH%
  - cmd: cd C:\projects\triton
  - cmd: mkdir build
  - cmd: cd build
  - cmd: echo Downloading z3...
  - cmd: appveyor DownloadFile https://github.com/Z3Prover/z3/releases/download/z3-4.8.9/%Z3_PKG_NAME%.zip
  - cmd: 7z x %Z3_PKG_NAME%.zip
    # Install z3 in the path
  - set PATH=C:\projects\triton\build\%Z3_PKG_NAME%\bin;%PATH%
  - set PYTHONPATH=C:\projects\triton\build\%Z3_PKG_NAME%\bin\python;%PYTHONPATH%
  - cmd: echo Downloading capstone...
  - cmd: appveyor DownloadFile https://github.com/aquynh/capstone/archive/4.0.2.zip
  - cmd: 7z x 4.0.2.zip
  - cmd: echo Building capstone...
# This is required because capstone's slns/vcxprojs file have been made with an old version of MSVC which is not a problem in itself,
# the issue will show up when trying to link capstone.lib (generated with an old toolset) into triton that is generated with the new toolset.
# This result in annoying linking errors (sprintf/and similar functions don't get resolved) - we could also link legacy_stdio_definitions.lib to triton
# but I would rather build everything I can with the same toolset:
#   http://stackoverflow.com/questions/32418766/c-unresolved-external-symbol-sprintf-and-sscanf-in-visual-studio-2015
# The switch /p:PlatformToolset allows you to override the toolset version specified in the solution/project files :-)
  - cmd: msbuild capstone-4.0.2\msvc\capstone.sln /p:Configuration=%configuration% /p:Platform=%platform% /p:PlatformToolset=%PLATFORM_TOOLSET% /t:capstone_static /m
    # Install LIEF
  - cmd: echo Downloading LIEF...
  - cmd: appveyor DownloadFile https://github.com/lief-project/LIEF/releases/download/%LIEF_VERSION%/%LIEF_ZIP%
  - cmd: echo Install LIEF...
  - cmd: python -m pip install %LIEF_ZIP%
    # Running cmake for Triton
  - cmd: echo Running cmake for Triton...
  - cmd: cmake -DBOOST_ROOT="C:/Libraries/boost_1_73_0" -DBoost_INCLUDE_DIR="C:/Libraries/boost_1_73_0" -DPYTHON_VERSION=%PYTHON_VERSION% .. -A %platform% -G "%CMAKE_TEMPLATE%"

#build:
# Build manually until we can build every target. For now, we can't run test-python
# target without installation
#  parallel: true
#  project: c:\projects\triton\build\triton.sln

build_script:
  - cmd: msbuild c:\projects\triton\build\triton.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:python-triton /m:3
    #  - cmd: cmake --build . --config release

test_script:
  - cmd: cmake --build . --config Release --target check

after_test:
  # Check installation
  - cmd: cmake --build . --config Release --target install

  # generate artifact
  - cmd: cd src\libtriton\%configuration%
  - cmd: copy ..\..\..\%Z3_PKG_NAME%\bin\libz3.dll libz3.dll
  - cmd: copy triton.dll triton.pyd
  - cmd: if "%platform%"=="Win32" 7z a -t7z ..\..\..\..\triton.x86.release.7z *
  - cmd: if "%platform%"=="x64" 7z a -t7z ..\..\..\..\triton.x64.release.7z *

artifacts:
  - path: triton.*.7z
